
POST HTTP://localhost:8000/cv/addCv
Content-Type: application/json

{
    "user_id": "5f09c5362125af1988dc247e",
    "address" : "rue dawha, 2129",
    "tel": "23884306",
    "linkedin": "https://www.linkedin.com/in/amani-bf/",
    "facebook" : "https://www.facebook.com/amani.bf/"
            
}

###

GET HTTP://localhost:8000/cv/AllCvs

###

DELETE HTTP://localhost:8000/cv/delete/5f0c3298d5280724fce1ba38

###

Patch HTTP://localhost:8000/cv/edit/5f0c3345d5280724fce1ba39
Content-Type: application/json

{
    "address" : "rue dawha, 29",
    "tel": "23884306",
    "linkedin": "https://www.linkedin.com/in/amani-bf/",
    "facebook" : "https://www.facebook.com/amani.bf/"
            
}

###

GET HTTP://localhost:8000/cv/getCv/5f0c3345d5280724fce1ba39