GET HTTP://localhost:3000/signUp

###

POST HTTP://localhost:3000/signUp
Content-Type: application/json

{
    "name": "amani",
    "last_name" : "ben farhat",
    "password": "23884306",
    "email": "benfarhatamani@gmail.com",
    "inscription_number" : "2233",
    "grade" : "1",
    "role" : "user"
            
}

###

POST HTTP://localhost:3000/login
Content-Type: application/json

{
    "email" : "benfarhatamani@gmail.com",
    "password" : "23884306"
            
}



